### ISSUE TITLE
Definir framework de UI

### ISSUE THREAD

**Issue by sampavalley** [sampavalley/liontax-calendar#1]
Precisamos de um WebApp (Android & Iphone). Utilizar Ionic ou outro framework de UI?

**Comment by rafaelcorreiapoli** [comment]
Opções:
1. Meteoric


2. Angular + Ionic 2


3. Angular + Ionic


4. Angular + Ionic Material


5. React + Material UI

**Comment by lnmunhoz** [comment]
Decidimos optar por **Framework7**
