### ISSUE TITLE
Mostrar quantos dias de estadia no Brasil

### ISSUE THREAD

**Issue by sampavalley** [sampavalley/liontax-calendar#13]
A principio o aplicativo só será para residentes do Brasil.

> A aquisição de residência fiscal também ocorrerá na data de obtenção de vínculo empregatício ou visto permanente se obtidos antes de se completar 184 dias de permanência no Brasil, dentro de um período de 12 meses. **[Extraido do Drive](https://drive.google.com/file/d/0B_UUYoAAWcMIY2h2RjBCOG5pcVk/view?usp=sharing)**

![travel calendar_home](https://cloud.githubusercontent.com/assets/16563021/12153738/adea5c68-b4a2-11e5-8ea7-a61a4cb33d6f.png)

**Comment by lnmunhoz** [comment]
Duplicated. Check #37
