### ISSUE TITLE
Login com Facebook & Linkedin

### ISSUE THREAD

**Issue by sampavalley** [sampavalley/liontax-calendar#2]

**Comment by rafaelcorreiapoli** [comment]
Registrei o App nas minhas contas pessoais do linkedin e facebook, mas devemos criar um email e nos registrar nessas redes sociais para manter a organização
@thiagobutignon, pode cuidar disso?
criar um email no gmail, sei lá: sampavalley.accounts@gmail.com
e se registrar no facebook e linkedin, etc... e me passar as credenciais? ai eu entro  lá e registro de novo o App

**Comment by lnmunhoz** [comment]
SIm @rafaelcorreiapoli, nos vamos criar duas configs de build. A de dev pode usar a suas keys mas a de production utiliza uma do email da Lion.

**Comment by rafaelcorreiapoli** [comment]
Já sabem o endereço que vai ficar hospedado? precisa colocar nas redirect URIs autorizadas, por enquanto tá só o localhost :baby:
