### ISSUE TITLE
Botão de logout

### ISSUE THREAD

**Issue by rafaelcorreiapoli** [sampavalley/liontax-calendar#24]
Precisamos de uma tela para colocar o botão de Logout
minha sugestão é criar uma terceira tab que é uma engrenagem
Lá temos uma lista com links pros termos de uso e política de privacidade, que são necessários
Pode também ter o nome do usuário logado (que a gente pega do facebook ou linkedin) ou que o cara pode setar caso faço login com password
Bom, tudo isso pra gente colocar o maldito botão de Logout lá hehe

**Comment by lnmunhoz** [comment]
É a parte do perfil do usuário, que ainda não fizemos wireframes. Mas é valido já colocar com o logout.

**Comment by rafaelcorreiapoli** [comment]
Preciso de ajuda com esse F7. Você já sacou qual classe que cria a view debaixo da appbar? as coisas tão ficando atrás dela, precisa de uma margin-top
isso também ta acontecendo na #5 travelsList

**Comment by lnmunhoz** [comment]
Precisa colocar na estrutura de view > pages > page.  A view precisa da classe `.navbar-fixed` e o conteúdo da page precisa estar dentro do `.page-content`

**Comment by lnmunhoz** [comment]
Coloquei a estrutura nesse commit 985fcbc97bfd0facfe3e5b6e76d15c1dcb51da9d pra você ver. Já arrumei na `travels view`.
