### ISSUE TITLE
Cancelar após clicar em país de novo

### ISSUE THREAD

**Issue by sampavalley** [sampavalley/liontax-calendar#29]

**Comment by carolinaveira** [comment]
voltar e não cancelar

**Comment by rafaelcorreiapoli** [comment]
É sobre o fato de que, quando estamos adicionando uma viagem, ao clicar na lista de países e mudar o selecionado as informações preenchidas previamente são perdidas?

**Comment by rafaelcorreiapoli** [comment]
Se for, tá feito! :)
