### ISSUE TITLE
Melhorar area de toque do input de data

### ISSUE THREAD

**Issue by lnmunhoz** [sampavalley/liontax-calendar#42]
O input está com uma usabilidade ruim, pois precisa clicar direto na data e o texto é pequeno.

**Comment by rafaelcorreiapoli** [comment]
![lioncalendar](https://cloud.githubusercontent.com/assets/12840136/12838471/a64ff5d8-cbb5-11e5-898b-202be37b7027.png)
Eu aumentei a altura do Input, toda a área em azul é passiva de abrir o calendário. Será que resolve?

**Comment by Lionpam** [comment]
Resolve, mas testei e ainda não esta funcionando. 

Enviado do meu iPhone

**Comment by rafaelcorreiapoli** [comment]
Ainda não subi a atualização, o App ainda está como o vocês viram na última reunião :)

**Comment by lnmunhoz** [comment]
Feito no commit 9df928f51afcb97a67ce8078c14867bf1ca7af10
